# Generated by Django 4.0.5 on 2022-07-13 12:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('total_leave', models.IntegerField(default=0)),
                ('past_total_leave', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.datetime(2022, 7, 13, 17, 41, 24, 650118))),
                ('end_date', models.DateField(null=True)),
                ('no_days_cleave', models.IntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('charge_handed_to', models.CharField(blank=True, max_length=50)),
                ('handed_fname', models.CharField(blank=True, max_length=50)),
                ('handed_designation', models.CharField(blank=True, max_length=50)),
                ('handed_date', models.DateField(null=True)),
                ('handed_end_date', models.DateField(null=True)),
                ('approval', models.BooleanField(default=False)),
                ('attachment', models.FileField(null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeadGenration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_name', models.CharField(max_length=30)),
                ('oreder_dispatch_mon', models.DateField()),
                ('site_name', models.CharField(max_length=100)),
                ('involved_dealer', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=800)),
                ('dev_arch', models.CharField(max_length=50)),
                ('dev_arch_name', models.CharField(max_length=100)),
                ('order_value', models.BigIntegerField(default=0)),
                ('pro_total_value', models.BigIntegerField(default=0)),
                ('total_unit', models.IntegerField(default=0)),
                ('total_wall_sqft', models.BigIntegerField(default=0)),
                ('total_floor', models.IntegerField(default=0)),
                ('remark', models.CharField(max_length=300)),
                ('attachment_front', models.FileField(null=True, upload_to='')),
                ('attachment_back', models.FileField(null=True, upload_to='')),
                ('auto_location', models.CharField(max_length=800)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HotProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_name', models.CharField(max_length=30)),
                ('visit_date', models.DateField()),
                ('site_name', models.CharField(max_length=100)),
                ('involved_dealer', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=800)),
                ('dev_arch', models.CharField(max_length=50)),
                ('dev_arch_name', models.CharField(max_length=100)),
                ('order_value', models.BigIntegerField(default=0)),
                ('pro_total_value', models.BigIntegerField(default=0)),
                ('total_unit', models.IntegerField(default=0)),
                ('total_wall_sqft', models.BigIntegerField(default=0)),
                ('total_floor', models.IntegerField(default=0)),
                ('remark', models.CharField(max_length=300)),
                ('constraction_stage', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=50)),
                ('contact_num', models.CharField(max_length=20)),
                ('total_floor_sqft', models.BigIntegerField(default=0)),
                ('site_type', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challanges', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=100)),
                ('feedback', models.CharField(max_length=800)),
                ('attachment', models.FileField(null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField(default=datetime.datetime(2022, 7, 13, 17, 41, 24, 651116))),
                ('payment_method', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=300)),
                ('approval_by', models.CharField(blank=True, max_length=100)),
                ('decline_reason', models.CharField(blank=True, max_length=300)),
                ('approved', models.BooleanField(default=False)),
                ('approval_date_finance', models.DateField()),
                ('approval_date_managment', models.DateField()),
                ('attachment', models.FileField(null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_location', models.CharField(max_length=800)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('logout_time', models.TimeField()),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
