# Generated by Django 4.0.5 on 2022-07-13 12:11

import account.models
import datetime
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('type', models.CharField(choices=[('DEALER', 'dealer'), ('MARKETING_PERSON', 'marketing_person'), ('ADMIN', 'admin')], default='MARKETING_PERSON', max_length=30)),
                ('fname', models.CharField(max_length=30, verbose_name='First Name')),
                ('lname', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('dob', models.DateField(default=datetime.date(2022, 7, 13), verbose_name='Date Of Birth')),
                ('mobile', models.CharField(max_length=10, unique=True, verbose_name='Phone Number')),
                ('alt_mobile', models.CharField(max_length=10, verbose_name='Alternative Number')),
                ('permanent_add', models.TextField(verbose_name='Permanenet Address')),
                ('current_add', models.TextField(verbose_name='Current Address')),
                ('state', models.CharField(max_length=30, verbose_name='State')),
                ('district', models.CharField(max_length=30, verbose_name='District')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('pincode', models.CharField(max_length=6, verbose_name='Pincode number')),
                ('blood_grp', models.CharField(max_length=3, verbose_name='Blood group')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=6, verbose_name='Sex')),
                ('adhar_num', models.CharField(max_length=50, verbose_name='Adhar Number')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', account.models.CustomeUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MarketingPersonAdditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_email', models.EmailField(max_length=254, verbose_name='Company Email Address')),
                ('refrence', models.CharField(max_length=50, verbose_name='Reference')),
                ('past_job', models.CharField(max_length=80, verbose_name='Past Job')),
                ('joining_date', models.DateField(verbose_name='joining Date')),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Divorced', 'Divorced'), ('Single', 'Single')], max_length=20, verbose_name='Maritual Status')),
                ('Anniversary_date', models.DateField(verbose_name='Annivarsary Date')),
                ('spouse_name', models.CharField(max_length=30, verbose_name='Spouse Name')),
                ('spouse_dob', models.DateField(verbose_name='Spouse birth date')),
                ('emergency_contact_person', models.CharField(max_length=10, verbose_name='Emergency Contact Person')),
                ('emergency_contact_num', models.CharField(max_length=10, verbose_name='Emergency Contact Number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DealerProfileAdditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, verbose_name='Reference')),
                ('company_name', models.CharField(max_length=30, verbose_name='Company name')),
                ('company_dealing_address', models.TextField(verbose_name='Company Dealing Address')),
                ('company_key_person_name', models.CharField(max_length=30, verbose_name='Company Key Person Name')),
                ('company_key_person_number', models.CharField(max_length=10, verbose_name='Company Key Contact Name')),
                ('gst_number', models.CharField(max_length=15, unique=True, verbose_name='GST Number')),
                ('pan_number', models.CharField(max_length=10, unique=True, verbose_name='PAN Number')),
                ('current_handling_brand_or_companies', models.TextField(verbose_name='Current Handling Brand Or Companies')),
                ('product_type', models.CharField(choices=[('Fullbody', 'Fullbody'), ('PGVT', 'PGVT'), ('Both', 'Both')], default=None, max_length=8, verbose_name='Product Type')),
                ('other_branch_dealings', models.CharField(max_length=250, verbose_name='Other Branch Dealings')),
                ('present_showroom_sq_ft', models.CharField(max_length=200, verbose_name='Present Showroom Sq. Ft.')),
                ('present_godown_sq_ft', models.CharField(max_length=200, verbose_name='Present Godown Sq. Ft.')),
                ('distance_from_showroom_to_godown', models.CharField(max_length=200, verbose_name='Distance From Showrrom To Godown')),
                ('showroom_owned_or_leased', models.CharField(max_length=200, verbose_name='Showroom Owned Or Leased')),
                ('off_day_in_week_in_market', models.CharField(max_length=15, verbose_name='Off Day In Week In Market')),
                ('space_provided_to_casa', models.CharField(max_length=250, verbose_name='Space Provided To CASA')),
                ('past_job', models.CharField(max_length=30, verbose_name='Past Job')),
                ('joining_date', models.DateField(verbose_name='Joining Date')),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Divorced', 'Divorced'), ('Single', 'Single')], default=None, max_length=9, verbose_name='Marital Status')),
                ('anniversary_date', models.DateField(verbose_name='Anniversary Date')),
                ('spouse_name', models.CharField(max_length=30, verbose_name='Spouse Name')),
                ('spouse_date_of_birth', models.DateField(verbose_name='Spouse Date of Birth')),
                ('emergency_contact_person', models.CharField(max_length=30, verbose_name='Emergency Contact Person')),
                ('emergency_contact_person_phone_number', models.CharField(max_length=10, verbose_name="Emergency Contact Person's Phone Number")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DealerProfile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.customeuser',),
        ),
        migrations.CreateModel(
            name='MarketingPersonProfile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.customeuser',),
        ),
    ]
