# Generated by Django 4.0.5 on 2022-07-13 13:22

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofileadditional',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=account.models.DealerProfileAdditional.path_and_rename),
        ),
    ]
