# Generated by Django 4.0.5 on 2022-07-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_dealerprofileadditional_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, verbose_name='Sex'),
        ),
    ]
