# Generated by Django 4.0.5 on 2022-07-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_dealerprofileadditional_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingpersonadditional',
            name='joining_date',
            field=models.DateField(blank=True, verbose_name='joining Date'),
        ),
    ]
