# Generated by Django 4.0.5 on 2022-07-14 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_marketingpersonadditional_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingpersonadditional',
            name='joining_date',
            field=models.DateField(default=datetime.date(2022, 7, 14), verbose_name='joining Date'),
        ),
    ]
