# Generated by Django 4.0.5 on 2022-07-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_marketingpersonadditional_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingpersonadditional',
            name='Anniversary_date',
            field=models.DateField(null=True, verbose_name='Annivarsary Date'),
        ),
    ]
