# Generated by Django 4.0.5 on 2022-07-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_marketingpersonadditional_anniversary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingpersonadditional',
            name='spouse_dob',
            field=models.DateField(null=True, verbose_name='Spouse birth date'),
        ),
    ]
