# Generated by Django 4.0.5 on 2022-07-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_marketingpersonadditional_spouse_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerprofileadditional',
            name='anniversary_date',
            field=models.DateField(null=True, verbose_name='Anniversary Date'),
        ),
        migrations.AlterField(
            model_name='dealerprofileadditional',
            name='joining_date',
            field=models.DateField(null=True, verbose_name='Joining Date'),
        ),
        migrations.AlterField(
            model_name='dealerprofileadditional',
            name='spouse_date_of_birth',
            field=models.DateField(null=True, verbose_name='Spouse Date of Birth'),
        ),
    ]
