# Generated by Django 4.0.5 on 2022-07-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_dealerprofileadditional_anniversary_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerprofileadditional',
            name='product_type',
            field=models.CharField(blank=True, choices=[('Fullbody', 'Fullbody'), ('PGVT', 'PGVT'), ('Both', 'Both')], default=None, max_length=8, verbose_name='Product Type'),
        ),
    ]
