# Generated by Django 4.0.5 on 2022-07-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_dealerprofileadditional_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerprofileadditional',
            name='product_type',
            field=models.CharField(choices=[('Fullbody', 'Fullbody'), ('PGVT', 'PGVT'), ('Both', 'Both')], default=None, max_length=8, null=True, verbose_name='Product Type'),
        ),
    ]
